version: '3.7'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERURL=domain
      - SERVERPORT=51820 #optional
      - PEERS=peer1,peer2
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.12.12.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 172.120.0.7
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.120.0.6

  pihole:
    container_name: pihole_wireguard
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    expose:
      - "53"
      #- "67" # Only required if you are using Pi-hole as your DHCP server
      - "443"
    ports:
      - 36080:80
    environment:
      TZ: 'Europe/Madrid'
    env_file:
      - extras.env
    volumes:
      - './pihole/:/etc/pihole/'
      - './dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN) 
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.120.0.7

networks:
  containers:
    ipam:
      config:
        - subnet: 172.120.0.0/24
