version: "2.4"
services:
  tailscale:
    privileged: true
    hostname: tailscale
    image: tailscale/tailscale:latest
    container_name: tailscale
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    env_file:
      - tailscale.env
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE