version: '2'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    volumes:
      - "/openvpn/conf:/etc/openvpn"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped