version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      #- JELLYFIN_PublishedServerUrl=192.168.0.5 # Set the autodiscovery response domain or IP address
    volumes:
      - /jellyfin/library:/config
      - /jellyfin/tvseries:/data/tvshows
      - /jellyfin/movies:/data/movies
    ports:
      - 8096:8096 # Http webUI
      #- 8920:8920 # Https webUI (need to set up own certificate)
      #- 7359:7359/udp # Allows clients to discover Jellyfin on the local network
      #- 1900:1900/udp # Service discovery used by DNLA and clients.
    restart: unless-stopped