version: '3'

services:
  minecraft_server:
    image: itzg/minecraft-server
    container_name: minecraft_server
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: 1.19
      # needed for Paper versions before 1.14
      CONSOLE: "false"
    env_file:
      - properties.env
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
    ports:
      - 25565:25565
      - 29050:29050
    networks:
      - minecraft_net

networks:
  minecraft_net:
    name: minecraft_net
    ipam:
      driver: default