version: '3.6'

services:
  openwebui-ollama:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3080:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

  chatbot-ollama:
    image: ghcr.io/ivanfioravanti/chatbot-ollama:main
    ports:
      - 3000:3000
    environment:
      - DEFAULT_MODEL=mistral
      - OLLAMA_HOST=http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama-models:/ollama/models
    ports:
      - 11434:11434
    environment:
      - OLLAMA_MODELS=/ollama/models

