version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERURL=auto # dominio o ip publica del servidor
      - SERVERPORT=51820
      - PEERS=3 # Cantidad de configuraciones de clientes
      - PEERDNS=8.8.8.8
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - /wireguard/config:/config
      - /wireguard/lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped